---

- name: s3 bucket objects list
  amazon.aws.aws_s3:
    bucket: tc-maven
    mode: list
    region: us-east-1
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
  register: result
- name: debug
  debug:
    var: result.s3_keys[3]

- name: s3 download
  amazon.aws.aws_s3:
    bucket: tc-maven
    object: "{{result.s3_keys[3] | trim}}"
    dest: /tmp/second.war
    mode: get
    region: us-east-1
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
  register: download_op
- name: debugging
  debug:
    var: download_op
         
